### ISSUE TITLE
9: Java Practice & Conclusion

### ISSUE THREAD

**Issue by Starlight220** [ExcaliburFRC/FRC-Curriculum#25]
Write some classes that use as much as what is learned.
Maybe also work by team Git workflow.

**Comment by Starlight220** [comment]
An idea for a class/project:
Different String->String functions, that the user can switch between them.
All user-entered text other than commands is passed through the currently active function.

**Comment by Starlight220** [comment]
@spaderski look if you can use what is already in the /09/ folder.

**Comment by spaderski** [comment]
you please can to summarize all, and if you can **### _in Hebrew_** please?

**Comment by spaderski** [comment]
> An idea for a class/project:
> Different String->String functions, that the user can switch between them.
> All user-entered text other than commands is passed through the currently active function.

what it's that: "Different String->String functions, that the user can switch between them."???

**Comment by Starlight220** [comment]
the program has different modes that the user can switch between them
