### ISSUE TITLE
Drivetrain Subsystem

### ISSUE THREAD

**Issue by Starlight220** [ExcaliburFRC/FRC-Curriculum#38]
#### Hardware:
- 4x `CANSparkMax` (2 per side)
- 2x `Encoder` (1 per side)
- `AHRS` (gyro)

#### Functions:
- arcade drive (create a `DifferentialDrive` object, and use its `arcadeDrive()` function

**Comment by elon698** [comment]
@Starlight220 can you send the code from previous years so ill have an example l

**Comment by Starlight220** [comment]
It's https://github.com/ExcaliburFRC/InfiniteRecharge2020-NewRobot
